version: '3.8'
name: MiniRag

services:
  lightrag:
    build: .
    ports:
      - "127.0.0.1:9721:9721"
    volumes:
      - ./data/rag_storage:/app/data/rag_storage
      - ./data/inputs:/app/data/inputs
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - lightrag_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  lightrag_net:
    driver: bridge
